parameters:
  name: ''
  displayName: ''
  vmImage: ''
  stepsTemplate: ''
  staticOnly: false

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        static_debug:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "Debug"
        static_release:
          STATIC_LINK: "ON"
          CMAKE_CONFIG: "Release"
        ${{ if ne(parameters.staticOnly, 'true') }}:
          dynamic_debug:
            STATIC_LINK: "OFF"
            CMAKE_CONFIG: "Debug"
          dynamic_release:
            STATIC_LINK: "OFF"
            CMAKE_CONFIG: "Release"
    steps:
      - template: ${{ parameters.stepsTemplate }}
        parameters:
          ${{ if eq(parameters.vmImage, 'vs2017-win2016') }}:
            toolchain: vs2017
          ${{ if eq(parameters.vmImage, 'windows-2019') }}:
            toolchain: vs2019
