name: Build Pichi with Conan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      os:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.image }}
    steps:
      - name: Install Conan
        uses: conan-io/setup-conan@v1
      - name: Install Just
        uses: extractions/setup-just@v3
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build for Android
        if:   inputs.os == 'android'
        run:  just -f .justfile build-android
      - name: Build for iOS
        if:   inputs.os == 'ios'
        run:  just -f .justfile build-ios
      - name: Build for host
        if:   inputs.os != 'android' && inputs.os != 'ios'
        run:  just -f .justfile build
