name: Build Pichi with Conan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      os:
        required: true
        type: string
      args:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Conan on macOS
        if: ${{ inputs.image == 'macos-14' }}
        run: brew install conan go
      - name: Install Conan on non-macOS
        if: ${{ inputs.image != 'macos-14' }}
        uses: turtlebrowser/get-conan@v1.1
      - name: Install NASM for windows
        if: ${{ inputs.os == 'windows' }}
        run: choco install -y nasm
      - name: Export BoringSSL recipe into the Conan cache
        run: .conan/scripts/conan.sh export -k .conan/scripts/latest.lock boringssl
      - name: Export libmaxminddb recipe into the Conan cache
        run: .conan/scripts/conan.sh export -k .conan/scripts/latest.lock libmaxminddb
      - name: Build pichi recipe
        run: >
          .conan/scripts/conan.sh build -k .conan/scripts/latest.lock
          -p ${{ inputs.os }}
          ${{ inputs.args }}
          latest
