name: Build Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - artifact: pichi-linux-x86_64
            image: ubuntu-24.04
            os: linux
          - artifact: pichi-linux-aarch64
            image: ubuntu-24.04-arm
            os: linux
          - artifact: pichi-macos-x86_64
            image: macos-26-intel
            os: macos
          - artifact: pichi-macos-aarch64
            image: macos-26
            os: macos
          - artifact: pichi-freebsd-x86_64
            image: ubuntu-24.04
            os: freebsd
          - artifact: pichi-windows-x86_64
            image: windows-2025
            os: windows

    uses: ./.github/workflows/conan.yml
    with:
      image: ${{ matrix.image }}
      os: ${{ matrix.os }}
      artifact: ${{ matrix.artifact }}
      tag: ${{ github.ref_name }}
